### PR TITLE
Add Crafting Loop Toggle

### PR DESCRIPTION
**Pull request by rootdarkarchon**
As discussed on Discord, here is the PR for the Crafting Loop Toggle.

- can be set to infinite or to a specific amount
- can be toggled per macro
- can start from either crafting log or synthesis window depending on configuration

### CODE REVIEW

**Comment by daemitus** [comment]
https://github.com/daemitus/SomethingNeedDoing/commit/5750c52847886d5405ed1716bd2e13fc45c551cb

Whats your opinion on using the /craftloop command idea I had mentioned to you instead?
Instead of cluttering up the UI some more, we could place `/craftloop` or `/craftloop s`  for the "start in synthesis" option.  The inserts happen at the location of the command, the rest get placed at the end.

**Comment by daemitus** [comment]
in short-form `/cl 10` at the start of the macro and done.

**Comment by rootdarkarchon** [comment]
I suppose it's possible but from a UX perspective i feel a toggleable button is better. At least this way you can quickly switch between single craft and Looping something without adjusting the macro code. 
I'm not sure, I could probably also live with adding stuff to macros but i would prefer not to if that makes any sense

**Comment by daemitus** [comment]
https://github.com/daemitus/SomethingNeedDoing/commit/5c001e5e02711738408851e32a28a7b8e5318267

UI option, with some QoL like mousewheel on the loop#

**Comment by rootdarkarchon** [comment]
Looks good to me, thanks!

**Pull request closed without merging**
